/*
 * opencurry: fun.c
 *
 * Copyright (c) 2015, Byron James Johnson
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* stddef.h:
 *   - NULL
 */
#include <stddef.h>

#include "base.h"
#include "util.h"

#include "fun_base.h"

/* ---------------------------------------------------------------- */

/*
 * Return a val_t's prim_t output.
 *
 * Behaviour is undefined if "val" is a function value.
 */
prim_t val_out(val_t val)
{
  return val.out;
}

/*
 * val_call:
 *
 * Call a function and return the resulting val_t.
 */
val_t val_call(val_t val, val_t input)
{
  return val.fun(&val, input);
}

/*
 * call_out:
 *
 * Call a function and return the resulting val_t's prim_t output.
 */
prim_t call_out(val_t val, val_t input)
{
  return val_out(val_call(val, input));
}

/* ---------------------------------------------------------------- */

/*
 * Procedure function for values generated by "val_prim".
 *
 * Returns "self", ignoring "input".
 */
val_t val_prim_fun(const val_t *self, val_t input)
{
  return *self;
}

/*
 * val_prim:
 *
 * Create a function, paired with a pre-set output value equal to the provided
 * value, that returns itself on any input.
 */
val_t val_prim(prim_t prim)
{
  val_t val;

  val.out = prim;
  val.fun = val_prim_fun;

  return val;
}

/* ---------------------------------------------------------------- */

/*
val_t val_two_lazy_fun(const val_t *self, val_t input)
{
}

val_t val_two_lazy(val_t a, val_t b)
{
  val_t val;

  val.out_fun = a;

  return val;
}
*/

/* ---------------------------------------------------------------- */

/*
val_t val_two_fun(const val_t *self, val_t input)
{
}

val_t val_two(prim_t a, prim_t b)
{
  val_t val;

  val.out = a;
  val.fun = val_two_fun;

  return val;
}
*/

/*
/8
 * impure_val_strict_two_vals:
 *
 * Evaluates both values of a pair generated by TODO
 8/
void impure_val_strict_two_vals(val_t two, prim_t *ap, prim_t *bp)
{
  prim_t ap, bp;

  if(ap)
  {
    *ap = 
  }
}
*/

/*
/8
 * return_two:
 *
 * Create a function that returns "a" along with another function
 * that returns "".
 *
 * Example:
 *
 * > fun_s who_is_together = return_two('u', 'i');
 * > char first_result = who_is_together();
 8/
any_t return_two(any_t a, any_t b)
{
  any_t two_tuple;

  two_tuple.out = a;
  two_tuple.fun = ;

  return two_tuple;
}
*/
